services:
  node:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: s0obang/sswu_sonsaekim-node:${BUILD_NUMBER}
    container_name: sswu_sonsaekim-node
    ports:
      - "3000:3000"
    depends_on:
      - flask
    restart: always

  flask:
    build:
      context: ./flask_server
      dockerfile: ./Dockerfile
    image: s0obang/sswu_sonsaekim-flask:${BUILD_NUMBER}
    container_name: sswu_sonsaekim-flask
    ports:
      - "5000:5000"
    restart: always

